---
title: "Introduction to Quantum Mechanics Notebook"
author: "Geirmundur Orri Sigurdsson"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This is my notebook for studying of The "Introduction to Quantum Mechanics" third edition by D. J. Griffiths

# Dependencies

```{r dependencies, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
```

# 1

## 1.1

### Problem 1.1

```{r chapter 1 problem 1.1}
df <- data.frame(
  j = c(14, 15, 16, 22, 24, 25),
  n = c(1,1,3,2,2,5))
df <- df %>% mutate(
  jn = j * n,
  p  = n / sum(df$n))
df <- df %>% mutate(
  jp = j * p,
  j2 = j * j)
ej = sum(df$jp)
ej2 = ej * ej
df <- df %>% mutate(
  dj  = j - ej,
  j2p = j2 * p)
ej2p = sum(df$j2p)
df <- df %>% mutate(
  dj2 = dj * dj)
df <- df %>% mutate(
  dj2p = dj2 * p)
sdj2p = sum(sum(df$dj2p))
sdm1 = sqrt(sdj2p)
dej2pej = ej2p - ej * ej
sdm2 = sqrt(dej2pej)
kable(df, caption = "Summary")
```

a)

$$\left\langle j \right\rangle = `r toString(ej)`$$

$$\left\langle j \right\rangle ^{2} = `r toString(ej2)`$$

$$\left\langle j^{2} \right\rangle = \frac{1}{N} \sum_{}^{}j^{2}N\left( j \right) = `r toString(ej2p)`$$

b)

$$\sigma^{2} = \frac{1}{N} \sum_{}^{}\left( \Delta j \right)^{2}N\left( j \right) = `r toString(sdj2p)` \Rightarrow \sigma = \sqrt{`r toString(sdj2p)`} = `r toString(sdm1)`$$

c)

$$\sigma^{2} = \left\langle j^{2} \right\rangle - \left\langle j \right\rangle^{2} = `r toString(ej2p)` - `r toString(ej)`^{2} = `r toString(dej2pej)` \Rightarrow \sigma = \sqrt{`r toString(dej2pej)`} = `r toString(sdm2)`$$

## 1.2

### Example 1.2

$$x\left( t \right) = \frac{1}{2} g t^{t}$$

The probability density (Eq. 1.14)

$$\rho\left( x \right) = \frac{1}{2\sqrt{hx}},\left( 0\leqslant x\leqslant h \right)$$

The integral between 0 and h

Confirmed with [Integral Calculator](https://www.integral-calculator.com/)

$$\int_{0}^{h} \rho\left( x \right) dx = \int_{0}^{h} \frac{1}{2\sqrt{hx}} dx = \frac{1}{2\sqrt{h}}\left( 2x^{\frac{1}{2}} \right) \Big|_0^h = \frac{\sqrt{hx}}{h} \Big|_0^h = 1$$

The average distance (Eq. 1.17)

Confirmed with [Integral Calculator](https://www.integral-calculator.com/)

$$\left\langle x \right\rangle = \int_{0}^{h} x\cdot  \rho\left( x \right) dx = \int_{0}^{h} x\frac{1}{2\sqrt{hx}} dx = \frac{1}{2\sqrt{h}}\left( \frac{2}{3}x^{\frac{3}{2}} \right) \Big|_0^h = \frac{x^{2}}{3\sqrt{hx}} \Big|_0^h = \frac{h}{3}$$

### Problem 1.2

a)

The expected value of x squared

$$\left\langle x^{2} \right\rangle = \int_{0}^{h} x^{2}\cdot  \rho\left( x \right) dx = \int_{0}^{h} x^{2}\frac{1}{2\sqrt{hx}} dx = \frac{x^{3}}{5\sqrt{hx}} \Big|_0^h = \frac{h^{2}}{5}$$

The Standard deviation

$$\sigma^{2} = \left\langle x^{2} \right\rangle - \left\langle x \right\rangle^{2} = \frac{h^{2}}{5} - \left( \frac{h}{3} \right)^{2} = \frac{4}{45} h^{2} \Rightarrow \sigma = \frac{2}{3\sqrt{5}} h = 0.2981h$$

